Dev/add channel command
torchme/PostFinder pull request #23
Opened 2024-04-15 17:41 UTC by umbilnm

2024-05-03 13:19 UTC, mayb333 requested changes

2024-05-03 13:19 UTC, mayb333 commented on src/database/models.py
> +    username= Column(String, nullable=True)
че то непонятно за что эта колонка отвечает. Типо кто одобрил канал или какой пользователь запросил добавить?

2024-05-03 13:19 UTC, mayb333 commented on src/database/models.py
> +    members_count = Column(Integer, nullable=True)
это тоже непонятно. Прогони через гпт чтобы он тебе с названиями помог

2024-05-03 13:19 UTC, mayb333 commented on src/database/postgres_service.py
> +            channel=channel,
что тут с форматированием?

2024-05-03 13:19 UTC, mayb333 commented on src/database/models.py
> +class ChannelsPool(Base):
добавить бы какой-то channel_id - primary key

2024-05-03 13:19 UTC, mayb333 commented on src/database/postgres_service.py
> +        Check if a user with the given telegram_id exists in the database.
видимо дока от чего-то другого

2024-05-03 13:19 UTC, mayb333 commented on src/database/postgres_service.py
> +            query = select(ChannelsPool.channel, ChannelsPool.username)
кол-во подписчиков доставать не хочешь?

2024-05-03 13:19 UTC, mayb333 commented on src/handlers/admin.py
> +async def del_channel(message: types.Message, command: CommandObject):
а почему нет add_channeL?

2024-05-03 13:19 UTC, mayb333 commented on src/handlers/callbacks.py
> +        await pg_manager.add_user(telegram_id=user_id, username=username)
у тебя в этом запросе на добавление юзера к бд может быть ошибка, но ты уже отправил ему что аппрувд

2024-05-03 13:19 UTC, mayb333 commented on src/utils/validation.py
> +async def validate_add_channel_command_args(args_str: Optional[str]):
название конечно пиздец) я бы короче сделал

2024-05-05 19:11 UTC, umbilnm commented on src/config/config.yaml
> +      Error: Acces denied! You don't have rights for this.
это если пользователь будет юзать админские команды, то есть не с модерацией связано, оставлю так

2024-05-05 19:14 UTC, umbilnm commented on src/config/config.yaml
> +    parse_channel_error: |
одна для find другая add_channel, но в приницпе да, можно одну из них оставить

2024-05-05 19:24 UTC, umbilnm commented on src/handlers/admin.py
> +async def del_channel(message: types.Message, command: CommandObject):
есть, но она в commands, так как есть и у юзеров и у админов, там проверка на админа происходит

2024-05-06 14:09 UTC, mayb333 approved these changes

2024-05-07 01:15 UTC, merged